### ISSUE TITLE
配置中心

### ISSUE THREAD

**Issue by Lao-Feng** [apache/dubbo-website#1763]
一:  环境:  springboot版本dubbo 3.1.3  /  naocs 2.0.3

二:  maven依赖如下:
```
  <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>3.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-configcenter-nacos</artifactId>
            <version>3.1.3</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
           <version>2.0.3</version>
        </dependency>
```

三: 项目启动的配置文件: 
```
  dubbo:
  config-center:
    address: nacos://127.0.0.1:8848
    group: dubbo
    namespace: 4fc48c00-e259-4051-99cc-fa20642b2eff
    config-file: dubbo.yaml
```

四: nacos截图
   
![image](https://user-images.githubusercontent.com/35493712/209420451-fa0c15c3-4622-4783-8c58-3da5257604eb.png)

五: 问题: 
   1. 无法读取yaml文件, 启动会报错 ava.lang.IllegalStateException: No such any registry to reference com.tawa.product.client.InventoryClient on the consumer 192.168.137.1 use dubbo version 3.1.3, please config <dubbo:registry address="..." /> to your spring config.  
   (如果是properties格式, 能正常启动, 但是会有问题2)

  2. 在项目中, 无法读取配置文件, 比如  是无法读取的
        @Value("${dubbo.registry.address}")
         private String config;
